# Generated by Django 4.0.4 on 2025-07-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviso', models.CharField(max_length=255, verbose_name='Aviso')),
                ('fecha_inicial', models.DateField(verbose_name='Inicia prom.')),
                ('fecha_final', models.DateField(verbose_name='finaliza prom.')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'db_table': 'Aviso',
                'ordering': ['fecha_inicial'],
            },
        ),
    ]
