# Generated by Django 4.0.4 on 2025-07-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vehiculo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiculo',
            unique_together={('nombre',)},
        ),
    ]
