# Generated by Django 4.0.4 on 2025-07-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vehiculo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='estatus',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=True, verbose_name='Activo'),
        ),
    ]
