# Generated by Django 4.0.4 on 2025-07-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='orden',
            field=models.IntegerField(default=1, verbose_name='Orden visual'),
        ),
    ]
