# Generated by Django 4.0.4 on 2025-07-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_menu_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['menu'], 'verbose_name': 'Menú', 'verbose_name_plural': 'Menús'},
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('menu',)},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
        migrations.CreateModel(
            name='MenuOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden visual')),
                ('descripcion', models.CharField(max_length=60, verbose_name='texto menú')),
                ('imagen', models.CharField(max_length=100, verbose_name='Imagen menú')),
                ('url', models.CharField(max_length=100, verbose_name='Url')),
                ('estatus', models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('menus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menu')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
                'db_table': 'MenuOpciones',
                'ordering': ['menus', 'orden'],
                'unique_together': {('menus', 'orden')},
            },
        ),
    ]
