# Generated by Django 5.2.4 on 2025-08-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_menu_options_alter_menu_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='orden',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
    ]
