# Generated by Django 5.2.4 on 2025-08-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aviso_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'ordering': ['orden', 'fecha_inicial'], 'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
        migrations.AddField(
            model_name='aviso',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='mensajes/', verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='fecha_final',
            field=models.DateField(blank=True, null=True, verbose_name='Finaliza prom.'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='fecha_inicial',
            field=models.DateField(blank=True, null=True, verbose_name='Inicia prom.'),
        ),
    ]
