# Generated by Django 5.2.4 on 2025-08-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_aviso_options_aviso_icono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Clientes'), (1, 'Talleres'), (2, 'Administradores')], default=0, verbose_name='Tipo'),
        ),
    ]
