# Generated by Django 5.2.4 on 2025-08-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aviso_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'ordering': ['tipo', 'fecha_inicial'], 'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='orden',
        ),
    ]
