# Generated by Django 5.2.4 on 2025-08-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_aviso_options_remove_aviso_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='icono',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Ícono'),
        ),
    ]
