# Generated by Django 5.2.4 on 2025-08-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_aviso_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='icono',
            field=models.CharField(choices=[('transporte', '🚚 Transporte'), ('dinero', '💰 Dinero'), ('regalo', '🎁 Regalo')], default=1, max_length=80, verbose_name='Ícono'),
        ),
    ]
