# Generated by Django 5.2.4 on 2025-08-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_aviso_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulo')),
                ('texto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto')),
                ('detalle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalle')),
                ('mas_detalle', models.TextField(blank=True, null=True, verbose_name='Más detalle')),
                ('fecha_inicial', models.DateTimeField(blank=True, null=True, verbose_name='Inicia prom.')),
                ('fecha_final', models.DateTimeField(blank=True, null=True, verbose_name='Finaliza prom.')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'PromocionEspecial',
                'ordering': ['titulo', 'texto', 'fecha_inicial'],
            },
        ),
    ]
