# Generated by Django 5.2.4 on 2025-08-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_recomendaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recomendaciones',
            new_name='Recomendacion',
        ),
    ]
