# Generated by Django 5.2.4 on 2025-08-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_recomendaciones_recomendacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recomendaciones/', verbose_name='Imagen'),
        ),
    ]
