# Generated by Django 5.2.4 on 2025-09-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_recomendacion_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre')),
                ('correo', models.CharField(blank=True, max_length=255, null=True, verbose_name='correo')),
                ('asunto', models.CharField(blank=True, max_length=255, null=True, verbose_name='asunto')),
                ('contenido', models.TextField(blank=True, null=True, verbose_name='contenido')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'Consulta',
                'ordering': ['-creado'],
            },
        ),
    ]
