# Generated by Django 5.2.4 on 2025-09-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_consultas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consultas',
            new_name='Consulta',
        ),
    ]
