# Generated by Django 5.2.4 on 2025-09-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_consultas_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='respuesta',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='asunto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='contenido',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='correo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo'),
        ),
    ]
