# Generated by Django 5.2.4 on 2025-07-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0002_rename_venta_ventapaypal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventapaypal',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ventapaypal',
            name='cp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ventapaypal',
            name='direccion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ventapaypal',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ventapaypal',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventapaypal',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ventapaypal',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ventapaypal',
            name='pais',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
