# Generated by Django 5.2.4 on 2025-07-31 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0003_ventapaypal_ciudad_ventapaypal_cp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inventario', models.CharField(blank=True, max_length=64, null=True, verbose_name='Id primario')),
                ('id_empresa', models.CharField(blank=True, max_length=64, null=True, verbose_name='Id empresa')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventaweb.ventapaypal')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'db_table': 'VentaDetalle',
                'ordering': ['venta', 'id_empresa', 'id_inventario'],
            },
        ),
    ]
