# Generated by Django 5.2.4 on 2025-08-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0004_ventadetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Por surtir'), (1, 'Surtido')], default=0, verbose_name='Estatus'),
        ),
    ]
