# Generated by Django 5.2.4 on 2025-08-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0005_ventadetalle_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrega'),
        ),
    ]
