# Generated by Django 5.2.4 on 2025-08-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0006_ventadetalle_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='fecha_entrega',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Entrega'),
        ),
    ]
