# Generated by Django 5.2.4 on 2025-08-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0007_alter_ventadetalle_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario'),
        ),
    ]
