# Generated by Django 5.2.4 on 2025-08-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0009_alter_ventadetalle_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Pedido'),
        ),
    ]
