# Generated by Django 5.2.4 on 2025-08-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0010_ventadetalle_fecha_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='token_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
