# Generated by Django 5.2.4 on 2025-08-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0011_ventadetalle_token_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglasComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inventario', models.CharField(blank=True, max_length=64, null=True, verbose_name='Id inventario')),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ancho')),
                ('alto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Alto')),
                ('rin', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rin')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('id_empresa', models.CharField(blank=True, max_length=64, null=True, verbose_name='Id empresa')),
                ('tipo', models.IntegerField(choices=[(0, 'Porcentaje'), (1, 'Monto')], default=0, verbose_name='Tipo')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad')),
                ('estatus', models.IntegerField(choices=[(0, 'Vencida'), (1, 'Vigente')], default=1, verbose_name='Estatus')),
                ('fecha_inicial', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Inicia')),
                ('fecha_final', models.DateTimeField(auto_now=True, null=True, verbose_name='Termina')),
            ],
            options={
                'verbose_name': 'Regla',
                'verbose_name_plural': 'Reglas',
                'db_table': 'ReglasComision',
                'ordering': ['fecha_inicial', 'fecha_final'],
            },
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='deposito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deposito'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='estatus_comision',
            field=models.IntegerField(choices=[(0, 'Para comisión'), (1, 'Comisión cobrada')], default=0, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario'),
        ),
    ]
