# Generated by Django 5.2.4 on 2025-08-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0012_reglascomision_ventadetalle_comision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='fecha_pago_comision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pago comisión'),
        ),
    ]
