# Generated by Django 5.2.4 on 2025-08-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0013_ventadetalle_fecha_pago_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='estatus_comision',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Pagada')], default=0, verbose_name='Estatus'),
        ),
    ]
