# Generated by Django 5.2.4 on 2025-08-09 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0011_alter_taller_id_empresa'),
        ('ventaweb', '0014_alter_ventadetalle_estatus_comision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventadetalle',
            options={'ordering': ['venta', 'empresa', 'id_inventario'], 'verbose_name': 'Detalle', 'verbose_name_plural': 'Detalles'},
        ),
        migrations.RemoveField(
            model_name='ventadetalle',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='taller.taller', to_field='id_empresa'),
        ),
    ]
