# Generated by Django 5.2.4 on 2025-08-09 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0011_alter_taller_id_empresa'),
        ('ventaweb', '0015_alter_ventadetalle_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglascomision',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='reglascomision',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas', to='taller.taller', to_field='id_empresa'),
        ),
    ]
