# Generated by Django 5.2.4 on 2025-08-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0016_remove_reglascomision_id_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rasón social'),
        ),
    ]
