# Generated by Django 5.2.4 on 2025-08-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0017_ventadetalle_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrega'),
        ),
    ]
