# Generated by Django 5.2.4 on 2025-08-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0018_alter_ventadetalle_fecha_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglascomision',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='reglascomision',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='reglascomision',
            name='id_inventario',
        ),
        migrations.AddField(
            model_name='reglascomision',
            name='talleres',
            field=models.IntegerField(choices=[(0, 'Ninguno'), (1, 'Todos')], default=0, verbose_name='Talleres'),
        ),
    ]
