# Generated by Django 5.2.4 on 2025-08-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0019_remove_reglascomision_alto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglascomision',
            name='creado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='reglascomision',
            name='modificado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='reglascomision',
            name='fecha_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termina'),
        ),
        migrations.AlterField(
            model_name='reglascomision',
            name='fecha_inicial',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicia'),
        ),
        migrations.AlterField(
            model_name='reglascomision',
            name='talleres',
            field=models.BooleanField(choices=[(False, 'Ninguno'), (True, 'Todos')], default=False, verbose_name='Talleres'),
        ),
    ]
