# Generated by Django 5.2.4 on 2025-08-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0020_reglascomision_creado_reglascomision_modificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglascomision',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='reglascomision',
            name='rin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Rin'),
        ),
        migrations.AlterField(
            model_name='reglascomision',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(0, 'Porcentaje'), (1, 'Monto')], default=0, null=True, verbose_name='Tipo'),
        ),
    ]
