# Generated by Django 5.2.4 on 2025-08-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0021_alter_reglascomision_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglascomision',
            name='fecha_final',
            field=models.DateField(blank=True, null=True, verbose_name='Termina'),
        ),
        migrations.AlterField(
            model_name='reglascomision',
            name='fecha_inicial',
            field=models.DateField(blank=True, null=True, verbose_name='Inicia'),
        ),
    ]
