# Generated by Django 5.2.4 on 2025-08-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0022_alter_reglascomision_fecha_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='reglascomision',
            name='talleres',
            field=models.BooleanField(choices=[(False, ''), (True, 'Todos')], default=False, verbose_name='Talleres'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='estatus_comision',
            field=models.IntegerField(choices=[(0, 'No aplicó comisión'), (1, 'Por pagar'), (2, 'Pagada')], default=0, verbose_name='Estatus'),
        ),
    ]
