# Generated by Django 5.2.4 on 2025-08-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0023_ventadetalle_porcentaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='estatus_comision',
            field=models.IntegerField(choices=[(0, 'No aplicó comisión'), (1, 'Por pagar'), (2, 'Para depósito'), (3, 'Depositado')], default=0, verbose_name='Estatus'),
        ),
    ]
