# Generated by Django 5.2.4 on 2025-08-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0024_alter_ventadetalle_estatus_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='precio_unitario_s_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario s/iva'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario'),
        ),
    ]
