# Generated by Django 5.2.4 on 2025-09-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0025_ventadetalle_precio_unitario_s_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventapaypal',
            name='colonia',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
