# Generated by Django 5.2.4 on 2025-09-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaweb', '0026_ventapaypal_colonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventapaypal',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
