# Generated by Django 5.2.4 on 2025-08-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cliente',
            field=models.BooleanField(blank=True, null=True, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='taller',
            field=models.BooleanField(blank=True, null=True, verbose_name='Taller'),
        ),
    ]
