# Generated by Django 5.2.4 on 2025-08-03 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0010_alter_taller_estatus'),
        ('usuario', '0002_usuario_cliente_usuario_taller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cliente',
            new_name='is_cliente',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='taller',
            new_name='is_taller',
        ),
        migrations.AddField(
            model_name='usuario',
            name='taller1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller.taller'),
        ),
    ]
