# Generated by Django 5.2.4 on 2025-08-03 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_cliente_usuario_is_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='taller1',
            new_name='taller',
        ),
    ]
