# Generated by Django 5.2.4 on 2025-08-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_rename_taller1_usuario_taller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['last_name', 'materno', 'first_name'], 'permissions': (('usuarios', 'Consulta usuarios'),), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
