# Generated by Django 5.2.4 on 2025-08-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notificar',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Notificaciones'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_cliente',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_taller',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Taller'),
        ),
    ]
