# Generated by Django 5.2.4 on 2025-08-09 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0011_alter_taller_id_empresa'),
        ('usuario', '0006_usuario_notificar_alter_usuario_is_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='taller',
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_taller', to='taller.taller', to_field='id_empresa'),
        ),
    ]
