# Generated by Django 4.0.4 on 2025-06-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Rasón social')),
                ('direccion', models.CharField(max_length=256, verbose_name='Dirección')),
                ('numero_exterior', models.CharField(max_length=20, verbose_name='Núm. ext.')),
                ('numero_interior', models.CharField(max_length=20, verbose_name='Núm. ext.')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('codigo_postal', models.CharField(max_length=100, verbose_name='Código postal')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('telefono', models.CharField(max_length=40, verbose_name='Teléfono')),
                ('longitud', models.CharField(max_length=100, verbose_name='Longitud')),
                ('latitud', models.CharField(max_length=100, verbose_name='Latitud')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
        ),
    ]
