# Generated by Django 4.0.4 on 2025-06-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='direccion',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='latitud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='longitud',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Núm. ext.'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='numero_interior',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Núm. ext.'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='telefono',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Teléfono'),
        ),
    ]
