# Generated by Django 4.0.4 on 2025-06-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_alter_taller_codigo_postal_alter_taller_colonia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taller',
            options={'ordering': ['razon_social'], 'verbose_name': 'Taller', 'verbose_name_plural': 'Talleres'},
        ),
        migrations.AlterUniqueTogether(
            name='taller',
            unique_together={('razon_social',)},
        ),
        migrations.AlterModelTable(
            name='taller',
            table='Taller',
        ),
    ]
