# Generated by Django 4.0.4 on 2025-06-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_alter_taller_options_alter_taller_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='id_colonia',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Id colonia'),
        ),
        migrations.AddField(
            model_name='taller',
            name='id_estado',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Id estado'),
        ),
        migrations.AddField(
            model_name='taller',
            name='id_municipio',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Id municipio'),
        ),
    ]
