# Generated by Django 4.0.4 on 2025-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_taller_id_colonia_taller_id_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='estatus',
            field=models.CharField(choices=[(0, 'Existe'), (1, 'Nuevo'), (2, 'Modificado')], default=1, max_length=1, verbose_name='Estatus'),
        ),
    ]
