# Generated by Django 4.0.4 on 2025-06-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_taller_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Existe'), (1, 'Nuevo'), (2, 'Modificado'), (3, 'Para proceso')], default=1, max_length=1, verbose_name='Estatus'),
        ),
    ]
