# Generated by Django 4.0.4 on 2025-06-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_alter_taller_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='id_empresa',
            field=models.CharField(default=0, max_length=64, verbose_name='Id empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taller',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Existe'), (1, 'Nuevo'), (2, 'Modificado'), (3, 'Para proceso')], default=1, verbose_name='Estatus'),
        ),
    ]
