# Generated by Django 4.0.4 on 2025-06-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_taller_id_empresa_alter_taller_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='id_empresa',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Id empresa'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rasón social'),
        ),
    ]
