# Generated by Django 4.0.4 on 2025-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_alter_taller_id_empresa_alter_taller_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
    ]
