# Generated by Django 4.0.4 on 2025-06-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_alter_taller_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Existe'), (1, 'Nuevo'), (2, 'Modificado'), (3, 'Sin recepción')], default=1, verbose_name='Estatus'),
        ),
    ]
