# Generated by Django 5.2.4 on 2025-08-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0010_alter_taller_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='id_empresa',
            field=models.CharField(max_length=64, unique=True, verbose_name='Id empresa'),
        ),
    ]
