# Generated by Django 5.2.4 on 2025-08-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0011_alter_taller_id_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='modificado',
        ),
    ]
