# Generated by Django 5.2.4 on 2025-08-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0012_remove_taller_modificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='talleres', verbose_name='Imagen'),
        ),
    ]
