# Generated by Django 5.2.4 on 2025-08-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0013_taller_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='talleres/', verbose_name='Imagen'),
        ),
    ]
