# Generated by Django 4.0.4 on 2025-06-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaLlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Marca')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'MarcaLlanta',
                'ordering': ['nombre'],
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='Llanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Modelo')),
                ('ancho', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ancho')),
                ('alto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alto')),
                ('rin', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rin')),
                ('radial', models.IntegerField(default=0, verbose_name='Radial')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.marcallanta')),
            ],
            options={
                'verbose_name': 'Llanta',
                'verbose_name_plural': 'Llantas',
                'db_table': 'Llanta',
                'ordering': ['marca', 'modelo', 'ancho', 'alto', 'rin'],
                'unique_together': {('marca', 'modelo', 'ancho', 'alto', 'rin')},
            },
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_clave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto/Clave')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio venta')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('llantas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.llanta')),
                ('talleres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taller.taller')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': 'Entrada',
                'ordering': ['talleres', 'producto_clave'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_clave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto/Clave')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('existencia', models.IntegerField(default=0, verbose_name='Existencia')),
                ('llantas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.llanta')),
                ('talleres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taller.taller')),
            ],
            options={
                'verbose_name': 'Llanta',
                'verbose_name_plural': 'Llantas',
                'db_table': 'Inventario',
                'ordering': ['talleres', 'producto_clave'],
                'unique_together': {('talleres', 'llantas'), ('talleres', 'producto_clave')},
            },
        ),
    ]
