# Generated by Django 4.0.4 on 2025-06-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='alto',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Alto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ancho',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ancho'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_empresa',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Id empresa'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_inventario',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Id primario'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='rin',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Rin'),
        ),
    ]
