# Generated by Django 4.0.4 on 2025-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_inventario_alto_inventario_ancho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Existe'), (1, 'Nuevo'), (2, 'Modificado'), (3, 'Para proceso')], default=1, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='llanta',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
    ]
