# Generated by Django 4.0.4 on 2025-06-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_inventario_creado_inventario_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Alto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ancho'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='rin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rin'),
        ),
    ]
