# Generated by Django 4.0.4 on 2025-06-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_alter_inventario_alto_alter_inventario_ancho_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Existe'), (1, 'Nuevo'), (2, 'Modificado'), (3, 'Sin recepción')], default=1, verbose_name='Estatus'),
        ),
    ]
