# Generated by Django 4.0.4 on 2025-07-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_alter_inventario_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='actualizado',
            field=models.IntegerField(choices=[(False, 'SI'), (True, 'No')], default=False, verbose_name='Actualizado'),
        ),
    ]
