# Generated by Django 4.0.4 on 2025-07-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_inventario_actualizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llanta',
            name='modelo',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Modelo'),
        ),
    ]
