# Generated by Django 5.2.4 on 2025-07-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_alter_llanta_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado'),
        ),
    ]
