# Generated by Django 5.2.4 on 2025-07-29 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0010_alter_inventario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['talleres', 'ancho', 'alto', 'rin'], 'verbose_name': 'Llanta', 'verbose_name_plural': 'Llantas'},
        ),
    ]
