# Generated by Django 5.2.4 on 2025-08-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0011_alter_inventario_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventarioPaso',
        ),
    ]
