# Generated by Django 5.2.4 on 2025-08-09 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0012_delete_inventariopaso'),
        ('taller', '0011_alter_taller_id_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llantas', to='taller.taller', to_field='id_empresa'),
        ),
    ]
