# Generated by Django 5.2.4 on 2025-08-10 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0013_inventario_empresa'),
        ('taller', '0011_alter_taller_id_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechazos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inventario', models.CharField(blank=True, max_length=64, null=True, verbose_name='Id primario')),
                ('id_empresa', models.CharField(blank=True, max_length=64, null=True, verbose_name='Id empresa')),
                ('producto_clave', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto/Clave')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ancho')),
                ('alto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Alto')),
                ('rin', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rin')),
                ('existencia', models.IntegerField(default=0, verbose_name='Existencia')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('actualizado', models.IntegerField(choices=[(False, 'SI'), (True, 'No')], default=False, verbose_name='Actualizado')),
                ('estatus', models.IntegerField(choices=[(0, 'Existe'), (1, 'Nuevo'), (2, 'Modificado'), (3, 'Sin recepción')], default=1, verbose_name='Estatus')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado')),
                ('llantas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.llanta')),
                ('talleres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taller.taller')),
            ],
            options={
                'verbose_name': 'Llanta',
                'verbose_name_plural': 'Llantas',
                'db_table': 'Rechazo',
                'ordering': ['talleres', 'ancho', 'alto', 'rin'],
            },
        ),
    ]
