# Generated by Django 5.2.4 on 2025-08-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0014_rechazos'),
        ('taller', '0011_alter_taller_id_empresa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rechazos',
            new_name='Rechazo',
        ),
    ]
