# Generated by Django 5.2.4 on 2025-08-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0015_rename_rechazos_rechazo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rechazo',
            options={'ordering': ['ancho', 'alto', 'rin'], 'verbose_name': 'Llanta', 'verbose_name_plural': 'Llantas'},
        ),
        migrations.RemoveField(
            model_name='rechazo',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='rechazo',
            name='llantas',
        ),
        migrations.RemoveField(
            model_name='rechazo',
            name='talleres',
        ),
        migrations.AlterField(
            model_name='rechazo',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Existe'), (1, 'Nuevo'), (2, 'Modificado'), (3, 'Sin recepción')], default=0, verbose_name='Estatus'),
        ),
    ]
