# Generated by Django 5.2.4 on 2025-08-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0016_alter_rechazo_options_remove_rechazo_actualizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='modificado',
        ),
        migrations.RemoveField(
            model_name='llanta',
            name='modificado',
        ),
        migrations.RemoveField(
            model_name='marcallanta',
            name='modificado',
        ),
        migrations.RemoveField(
            model_name='rechazo',
            name='modificado',
        ),
    ]
