# Generated by Django 5.2.4 on 2025-08-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0017_remove_inventario_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['empresa', 'descripcion'], 'verbose_name': 'Llanta', 'verbose_name_plural': 'Llantas'},
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='id_empresa',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='llantas',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='talleres',
        ),
    ]
