# Generated by Django 5.2.4 on 2025-08-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0018_alter_inventario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
    ]
