# Generated by Django 5.2.4 on 2025-08-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0019_inventario_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='almacen/', verbose_name='Imagen'),
        ),
    ]
