# Generated by Django 5.2.4 on 2025-09-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0020_inventario_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='imagen',
            new_name='imagenes',
        ),
        migrations.AddField(
            model_name='inventario',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='almacen1/', verbose_name='Imagen'),
        ),
    ]
