# Generated by Django 5.2.4 on 2025-09-05 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0021_rename_imagen_inventario_imagenes_inventario_imagen1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='imagenes',
            new_name='imagen',
        ),
    ]
